export const POST_LOGIN_REQUEST = "POST_LOGIN_REQUEST";
export const POST_LOGIN_SUCCESS = "POST_LOGIN_SUCCESS";
export const POST_LOGIN_ERROR = "POST_LOGIN_ERROR";

export const SET_USER_LOGIN = "SET_USER_LOGIN";
export const SET_USER_PASSWORD = "SET_USER_PASSWORD";

export const SET_USER_TOKEN = "SET_USER_TOKEN";
export const SET_USER_DATA = "SET_USER_DATA";

export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_ERROR = "LOGOUT_USER_ERROR";

export const AUTH_KEY = "x-auth";
export const AUTH_CHECKED = "AUTH_CHECKED";

//===SOCKET
export const SOCKET_CONNECT = "SOCKET_CONNECT";
export const SOCKET_DISCONNECT = "SOCKET_DISCONNECT";

//===GROUPS
export const GET_ALL_GROUPS_REQUEST = "GET_ALL_GROUPS_REQUEST";
export const GET_ALL_GROUPS_SUCCESS = "GET_ALL_GROUPS_SUCCESS";
export const GET_ALL_GROUPS_ERROR = "GET_ALL_GROUPS_ERROR";

export const GET_GROUP_STUDENTS_REQUEST = "GET_GROUP_STUDENTS_REQUEST";
export const GET_GROUP_STUDENTS_SUCCESS = "GET_GROUP_STUDENTS_SUCCESS";
export const GET_GROUP_STUDENTS_ERROR = "GET_GROUP_STUDENTS_ERROR";

export const UPDATE_ACTIVE = "UPDATE_ACTIVE";

//===QUIZZES
export const GET_ALL_QUIZZES_REQUEST = "GET_ALL_QUIZZES_REQUEST";
export const GET_ALL_QUIZZES_SUCCESS = "GET_ALL_QUIZZES_SUCCESS";
export const GET_ALL_QUIZZES_ERROR = "GET_ALL_QUIZZES_ERROR";

export const POST_QUIZ_REQUEST = "POST_QUIZ_REQUEST";
export const POST_QUIZ_SUCCESS = "POST_QUIZ_SUCCESS";
export const POST_QUIZ_ERROR = "POST_QUIZ_ERROR";

export const PATCH_QUIZ_REQUEST = "PATCH_QUIZ_REQUEST";
export const PATCH_QUIZ_SUCCESS = "PATCH_QUIZ_SUCCESS";
export const PATCH_QUIZ_ERROR = "PATCH_QUIZ_ERROR";

export const DELETE_QUIZ_REQUEST = "DELETE_QUIZ_REQUEST";
export const DELETE_QUIZ_SUCCESS = "DELETE_QUIZ_SUCCESS";
export const DELETE_QUIZ_ERROR = "DELETE_QUIZ_ERROR";

//===STATISTIC
export const GET_GROUP_STATISTICS_REQUEST = "GET_GROUP_STATISTICS_REQUEST";
export const GET_GROUP_STATISTICS_SUCCESS = "GET_GROUP_STATISTICS_SUCCESS";
export const GET_GROUP_STATISTICS_ERROR = "GET_GROUP_STATISTICS_ERROR";

//===STUDENT
export const ADD_QUIZ = "ADD_QUIZ";
export const DELETE_QUIZ = "DELETE_QUIZ";
// export const ADD_QUIZ_REQUEST = "DELETE_QUIZ_REQUEST";
// export const ADD_QUIZ_SUCCESS = "DELETE_QUIZ_SUCCESS";
// export const ADD_QUIZ_ERROR = "DELETE_QUIZ_ERROR";
